### ISSUE TITLE
Install instructions incomplete and other issues

### ISSUE THREAD

**Issue by RmaxTwice** [san4ezy/django_softdelete#1]
Hey, great and simple package, however I tried to use it and noticed there are a bit of missing instructions in the "Installation" section of the main readme.

The pip installation will not install this project but instead this one:  https://github.com/scoursen/django-softdelete
So I think a rename is in order.

- Do you need to add this package to the django project via the `INSTALLED_APPS` setting? if so what would be the name of the package? `django_softdelete`, `softdelete` or something else?
- What would the import statement look like when importing the `SoftDeleteModel` mixin into a `models.py`?

**Comment by san4ezy** [comment]
Hi, Rafael!
Thank you for the questions!
I just added the import lines into the examples.
Regarding the package name, you shouldn't add it to the installed apps list
or other things. Just install the package, import the needed class and use
them in your models/managers/querysets.
Good luck!
