### ISSUE TITLE
Consider adding tests

### ISSUE THREAD

**Issue by epicserve** [san4ezy/django_softdelete#14]
I was thinking of creating a soft delete Django package, but I thought I would check what was available. I think you're on the right track with your package, but before I use any package, I like to see tests and automated tests run in Github Actions or something similar.

**Comment by san4ezy** [comment]
Thank you @epicserve , good idea! I'm going to do that. If someone want and could make some tests, pls  don't be shy.

**Comment by jinimong** [comment]
> Thank you @epicserve , good idea! I'm going to do that. If someone want and could make some tests, pls don't be shy.

I will try this!

And, I think it has a bug about related manager actions.
I will fix it too soon. :)

**Comment by san4ezy** [comment]
Hi @epicserve 
The tests are available now.
