### ISSUE TITLE
No specified method to get only the deleted  objects.

### ISSUE THREAD

**Issue by Barnaan2** [san4ezy/django_softdelete#16]
i believe that this package is good but it lack some methods that are really helpful .

**Comment by san4ezy** [comment]
Hi @Barnaan2 ! Thank you! Could you please describe what particularly do you mean? I'm going to make some updates, so it would be nice if you have ideas for the library improvement.

**Comment by san4ezy** [comment]
Hello! As this issue is not discussed a lot of time, I'm closing it. If it is still actual, please reopent it and describe it more verbose. With an example please.
