### ISSUE TITLE
app_dirs must not be set when loaders is defined.

### ISSUE THREAD

**Issue by Odissine** [san4ezy/django_softdelete#18]
Hello
In my project "APP_DIRS"= True ... 
It seems because of loaders used for "this library" , I can't use this library at all :(
Is there a way to bypass this loaders ?

**Comment by san4ezy** [comment]
Hello! As this issue is not discussed a lot of time, I'm closing it. If it is still actual, please reopent it and describe it more verbose. With an example please.
