### ISSUE TITLE
Missing App Name for Django Settings

### ISSUE THREAD

**Issue by SeSartaj** [san4ezy/django_softdelete#19]
In the documentation, it would be greatly beneficial if you could explicitly mention the app name that should be added to the INSTALLED_APPS setting in the Django project's settings.py file. This addition will greatly assist users in correctly configuring the package within their Django projects.

**Comment by san4ezy** [comment]
The package name is `django_softdelete`. However, it is not necessary to add it to the `INSTALLED_APPS`. This package does not contain its own models, middleware, and so on, to be used directly in your project. Instead, it provides a set of abstract models and object managers that help you implement soft delete functionality with less effort.
