### ISSUE TITLE
Missing "get_related_fields" Functionality in Latest Version

### ISSUE THREAD

**Issue by vardgeskarapetyan2** [san4ezy/django_softdelete#21]
Hi @san4ezy @spockNinja,
I hope this message finds you well. I recently downloaded the latest version of library(https://pypi.org/project/django-soft-delete/). While reviewing the library, I noticed that the functionality reagarding get_related_fields function(https://github.com/san4ezy/django_softdelete/pull/20) doesn't exists in the latest version.
 I am interested to know when we can expect the release that includes this functionality.
Thank you for your time and attention to this matter.

**Comment by spockNinja** [comment]
Apologies, @vardgeskarapetyan2 -- but I haven't used this in a very long time. Even when I did, all I contributed was a very simple bugfix, unrelated to the `get_related_fields` function. Hopefully someone else will be able to help you out. 💚

**Comment by vardgeskarapetyan2** [comment]
Closing the issue as the logic with related fields already exists in new versions.
