### ISSUE TITLE
Soft delete and DELETE CASCADE

### ISSUE THREAD

**Issue by foucdeg** [san4ezy/django_softdelete#3]
I have this model:

```python
class MyParent(models.Model):
    # whatever

class MyModel(SoftDeleteModel):
    parent = models.ForeignKey(MyParent, on_delete=models.CASCADE)
```

What happens if I delete a Parent which has children MyModel? Does the child get physically deleted, or soft deleted and the foreign key set NULL?

**Comment by san4ezy** [comment]
Hi, @foucdeg !

Currently, the cascade deletion is not changed and it works as the Django standard functionality.

Soft-deletion works only with the models, you specifically inherit with the `SoftDeleteModel` class. This library overrides the model's `delete` method and the model queryset's `delete` method.

**Comment by foucdeg** [comment]
So the child does get physically deleted. It's probably a good thing to document.

**Comment by san4ezy** [comment]
Thanks! It's a good remark. I have documented it already.

**Comment by reyniel26** [comment]
How about this?
```
class MyParent(SoftDeleteModel):
    # whatever

class MyModel(SoftDeleteModel):
    parent = models.ForeignKey(MyParent, on_delete=models.CASCADE)
```
I tried to soft delete the parent yet the child model is not soft deleted.
How to soft delete the child model by soft deleting the parent ?

**Comment by sudarshaana** [comment]
> How about this?
> 
> ```
> class MyParent(SoftDeleteModel):
>     # whatever
> 
> class MyModel(SoftDeleteModel):
>     parent = models.ForeignKey(MyParent, on_delete=models.CASCADE)
> ```
> 
> I tried to soft delete the parent yet the child model is not soft deleted. How to soft delete the child model by soft deleting the parent ?

Facing same problem

**Comment by mahdisaibridge** [comment]
I'm facing the same problem here, should I use the Signal and handle it myself?
