### ISSUE TITLE
Automatic Restoration of Associated Objects in Django Models

### ISSUE THREAD

**Issue by sagnik036** [san4ezy/django_softdelete#35]
Class A:
  a = models.CharField()

Class B:
  b = models.ForeignKey(A)
  
In this code, when an object of class A is restored, all associated objects of class B are also restored, even if they were deleted earlier before deleting the object of class A. For instance, if you have a database of employees (class A) and their respective tasks (class B) when an employee is restored, all their tasks will also be restored, regardless of whether they were deleted previously.

**Comment by milosnikic** [comment]
@sagnik036 @san4ezy I've propose [PR](https://github.com/san4ezy/django_softdelete/pull/39) that will solve this issue.

**Comment by san4ezy** [comment]
Thanks @milosnikic 
Your PR was merged and the changes appear in version 1.0.14
