### ISSUE TITLE
DO NOT USE IT!!!!!!

### ISSUE THREAD

**Issue by droomo** [san4ezy/django_softdelete#43]
This lib cannot handle relationships like OneToOne, etc.

**Comment by no-ask-star** [comment]
sure, i have the same problem, here is an example for you:

class Project(SoftDeleteModel):
    current_stage = models.OneToOneField("Stage", on_delete=models.CASCADE, related_name="current_stage", null=True)


class Stage(SoftDeleteModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

**Comment by san4ezy** [comment]
Thanks a lot @droomo for finding the critical bug and for a very eloquent heading )
The fixes are already made it the next package version will include them.

**Comment by ksylvan** [comment]
@droomo amf @no-ask-star are you using the latest version? 1.0.15? Can you try it so we can close this issue?
