### ISSUE TITLE
'SoftDeleteQuerySet' object has no attribute 'disticnt'

### ISSUE THREAD

**Issue by bjrukin** [san4ezy/django_softdelete#6]
Hello,
When I try to get distinct count of soft delete I get following error:
'SoftDeleteQuerySet' object has no attribute 'disticnt'

**Comment by san4ezy** [comment]
@bjrukin hello!
There is a typo at `disticnt`
SoftDeleteQuerySet has all standard queryset methods.
![image](https://user-images.githubusercontent.com/6237832/179577206-0fcd12c4-a84d-4b3c-8958-373e124e39a5.png)
